apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eve-frontend.fullname" . }}
type: Opaque
data:
  CLIENT_SECRET: {{ .Values.eve.client_secret | b64enc | quote }}
  CLIENT_ID: {{ .Values.eve.client_id | b64enc | quote }}
  REDIRECT_URL: {{ .Values.eve.redirect_url | b64enc | quote }}