apiVersion: v1
kind: Service
metadata:
  name: {{ include "eve-frontend.fullname" . }}
  labels:
    {{- include "eve-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{ if eq .Values.service.type  "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    {{- include "eve-frontend.selectorLabels" . | nindent 4 }}
