apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eve-backend.fullname" . }}
type: Opaque
data:
  CLIENT_SECRET: {{ .Values.eve.client_secret | b64enc | quote }}
  CLIENT_ID: {{ .Values.eve.client_id | b64enc | quote }}
  JDBC_DATABASE_USERNAME: {{ .Values.postgresql.auth.username | b64enc | quote }}
  JDBC_DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}