apiVersion: v1
kind: Service
metadata:
  name: eve-backend
  labels:
    {{- include "eve-backend.labels" . | nindent 4 }}
    spring-boot: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{ if eq .Values.service.type  "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    {{- include "eve-backend.selectorLabels" . | nindent 4 }}
