spring:
  application:
    name: eve-job-character-update
  main:
    web-application-type: none

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO